### ISSUE TITLE
radio stuck after stop

### ISSUE THREAD

**Issue by havena** [maca134/arma-nradio#11]
after stop a radio, i cant play a new one, i need reboot arma3.

**Comment by jschmidt92** [comment]
This Issue is still present, any idea if you'll be able to fix it any time soon.

The radio works great the first time you select a station and play it, but as soon as you select "Stop", the radio stops. But after the radio station stops and then you select another station and select "Play", it doesn't play anything anymore until you restart ArmA 3.

**Comment by klemmchr** [comment]
@InnovativeStudios You should notice that this repo wasn't maintained since July 15

**Comment by maca134** [comment]
this code is a proof of concept and was hoping others would get involved. Unfortunatly no one has. If you would this developed privately, Im happy to talk about prices

**Comment by klemmchr** [comment]
Unfortunately BattlEye seems to make such "heavy load" extensions not usable at all. My experience is that enabling BattlEye in combination with a signed version of this extension makes any internet radio stream shuttering and buffering all the time.

**Comment by maca134** [comment]
I dont think that is the case. I have never heard BE slowing down extensions....

**Comment by klemmchr** [comment]
I contacted Suter regarding this issue and he confirmed it but didn't really had a clue how this could happen.
